version: '3'

services:
  redis:
    image: redis:latest
    command: redis-server --appendonly yes
    volumes:
      - ./.data:/data
  app:
    build: .
    command: /opt/hurl/bin/hurl
    ports:
      - "7777:7777"
    depends_on:
      - redis

